[package]
name = "majsoulmax-tauri"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "majsoulmax_tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
majsoul_max_rs = { git = "https://github.com/Xerxes-2/MajSoulMax-rs.git", tag = "v0.6.1" }
anyhow = "1.0.93"
tokio = { version = "1", features = ["rt-multi-thread"] }
tauri-plugin-log = { version = "2", features = ["colored"] }
log = "0.4"
